---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - java
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "testcpv"
exclude_paths:
- config/
- spec/
